//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// <regex>

// class regex_token_iterator<BidirectionalIterator, charT, traits>

// bool operator==(const regex_token_iterator& right) const;
// bool operator==(default_sentinel_t) const { return *this == regex_token_iterator(); } // since C++20
// bool operator!=(const regex_token_iterator& right) const; // generated by the compiler in C++20

#include <cassert>
#include <iterator>
// Ported from LLVM 242ccbf6b6d9d090762a87138c854f2d93b6ab60/re.iter/re.tokiter/re.tokiter.comp/equal.pass.cpp
// See test/libcxx_regex/manifest.json for all adaptations to this test.
#include "adapter.h"

#include "test_comparisons.h"
#include "test_macros.h"

int main(int, char**) {
#if TEST_STD_VER >= 20
  AssertEqualityReturnBool<libcxx_fixed_regex::cregex_token_iterator>();

  {
    libcxx_fixed_regex::cregex_token_iterator i;
    assert(testEquality(i, std::default_sentinel, true));
  }

  AssertEqualityReturnBool<libcxx_fixed_regex::sregex_token_iterator>();

  {
    libcxx_fixed_regex::sregex_token_iterator i;
    assert(testEquality(i, std::default_sentinel, true));
  }
#endif

  {
    libcxx_fixed_regex::regex phone_numbers("\\d{3}-\\d{4}");
    const char phone_book[] = "start 555-1234, 555-2345, 555-3456 end";
    libcxx_fixed_regex::cregex_token_iterator i(std::begin(phone_book), std::end(phone_book) - 1, phone_numbers, -1);
    assert(i != libcxx_fixed_regex::cregex_token_iterator());
    assert(!(i == libcxx_fixed_regex::cregex_token_iterator()));
    libcxx_fixed_regex::cregex_token_iterator i2 = i;
    assert(i2 == i);
    assert(!(i2 != i));
    ++i;
    assert(!(i2 == i));
    assert(i2 != i);
  }

  return 0;
}
