name: Windows

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main


env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ github.workflow }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
          restore-keys: |
            ${{ runner.os }}-${{ env.BUILD_TYPE }}-
          path: |
            ./vcpkg
            ~/vcpkg
            ./build/vcpkg_installed
            ${{ env.HOME }}/.cache/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
            "**/cpm_modules"

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true
          cmake: true
          ninja: true
          conan: false
          vcpkg: true
          ccache: true
          clangtidy: false
          cppcheck: true
          gcovr: false
          opencppcoverage: true

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=C:\Users\runneradmin\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        run: cmake --build build --config Debug -j4

      - name: Test
        working-directory: ./build
        run: |
          ctest --build-config Debug

      # TODO: add test and coverage for windows
      #- name: Test and coverage
      #  working-directory: ./build
      #  run: |
      #    OpenCppCoverage.exe --export_type cobertura:coverage.xml --cover_children -- ctest --build-config Debug
